### ISSUE TITLE
Temporarily does not support custom url

### ISSUE THREAD

**Issue by Lancger** [ugomeguerditchian/GoBoom#2]
It does not support the specification of suffix parameters. I hope it can be optimized to make this project more powerful.

I use this command to test the error？`go run GoBoom.go -d https://api.xxxx.com/shop/market/all -t 100 -m 2`

![1682636238023](https://user-images.githubusercontent.com/16274422/235008158-12e95a1e-fdb8-4c6e-a0ac-65b6c5504ce8.jpg)

**Comment by ugomeguerditchian** [comment]
This as been debug in the new version of V2 branch : https://github.com/ugomeguerditchian/GoBoom/commit/5d56ee0a1f14147dba0757f7fe489e9e2932490d

You have to use it like : go run GoBoom.go --get https://example.com

Remember that in this version (V2) the -t argument correspond to number of CPU core to be used when proxy mode is activated. Otherwise you have to set it in "-m 2" mode for non proxy mode and set the number of workers with the "-t"
